### ISSUE TITLE
Mirror mode not supported in Rice

### ISSUE THREAD

**Issue by emukidid** [emukidid/Wii64#64]
In Rice: Destruction Derby Professional mode, Diddy Kong Racing mirrored tracks and possibly more are broken. Mario Kart 64 is fine in "Extra" mode.

**Comment by carnage702** [comment]
this still needs to be addressed since it hasnt been fixed by 1.3 release.

**Comment by leodexe** [comment]
Too late to mention this now but Diddy Kong Racing just runs fine on Wii64 with glN64, which is the only supported graphic plugin by Not64. It runs fine without any of the bugs Rice has.

**Comment by carnage702** [comment]
> Too late to mention this now but Diddy Kong Racing just runs fine on Wii64 with glN64, which is the only supported graphic plugin by Not64. It runs fine without any of the bugs Rice has.

its the same error diddy kong racing uses mirror mode on tracks and adventure so any agme that mirrors maps will have this issue on rice since this fix was never implemented on rice sadly.

**Comment by leodexe** [comment]
Yeah... and I said it's fixed by playing Diddy Kong Racing on Not64, probably other games may get fixed as well, Mario Kart 64 and Cruisn' World are exceptions because they run better on Rice plugin which Not64 lacks.

**Comment by carnage702** [comment]
any chance to look at this emukid?

**Comment by emukidid** [comment]
Rice got some updates finally, try these all on 1.4.3 please https://github.com/emukidid/Wii64/releases/tag/1.4.3

**Comment by carnage702** [comment]
> Rice got some updates finally, try these all on 1.4.3 please https://github.com/emukidid/Wii64/releases/tag/1.4.3

just tried destruction derby professional mode on rice and its still broken on professional(mirror) everything is inside out graphically and right is left and left is right.

**Comment by emukidid** [comment]
This will be fixed in the next release, already fixed in code.
